name: 'test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: test-env
          create-args: >-
            python=${{matrix.python-version}}

      - name: Install package
        shell: bash -el {0}
        run: |
          python -m pip install -e .

      - name: run pytests
        shell: bash -el {0}
        run: |
          python -m pytest

